name: neuralnet
services:
  mnist:
    image: neuralnet:latest
    build: .
    volumes:
      - ./data:/neuralnet/data
    entrypoint: /bin/bash /neuralnet/network mnist
    restart: unless-stopped
    runtime: nvidia